### ISSUE TITLE
In the consumer side, the msgs are replicated in infinite loop and worker gives error.

### ISSUE THREAD

**Issue by Mukthi-Alva** [uber/uReplicator#100]
After starting the worker, when msgs are sent from producer to consumer, initial msg replication takes 5 mins to replicate. After that the msgs are replicated in infinite loop along with old replicated msg. Also the worker throws error as below:
[2017-12-01 08:04:37,174] ERROR Error when sending message to topic __consumer_offsets with key: 26 bytes, value: 24 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback:47)
java.lang.IllegalStateException: Producer is closed forcefully.
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:522)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortIncompleteBatches(RecordAccumulator.java:502)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:147)
	at java.lang.Thread.run(Thread.java:748)

Also getting error:

[2017-12-01 10:09:56,815] INFO Reset HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor:520)
[2017-12-01 10:09:56,815] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)

**Comment by xhl1988** [comment]
Looks like you are sending msg to topic __consumer_offsets which is not allowed. 

Did you enable auto-whitelisting?

**Comment by Mukthi-Alva** [comment]
Yes .. I have enabled auto white listing..

On Dec 4, 2017 7:39 PM, "xhl1988" <notifications@github.com> wrote:

Looks like you are sending msg to topic __consumer_offsets which is not
allowed.

Did you enable auto-whitelisting?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uber/uReplicator/issues/100#issuecomment-348972063>,
or mute
the thread

**Comment by xhl1988** [comment]
Please use "-patternToExcludeTopics" to exclude __consumer_offsets from auto-whitelisting.

**Comment by Mukthi-Alva** [comment]
This worked. Thank you!

**Comment by balboah** [comment]
Had the same problem, in my opinion this exclude pattern should be the default

**Comment by josdotso** [comment]
@xhl1988 

Why is mirroring `__consumer_offsets` not allowed?  Is this because uReplicator uses the old Kafka APIs? The oreilly book on Kafka gives some gotchas for mirroring that topic, but it may be useful for some folks.  Thanks!

**Comment by xhl1988** [comment]
No. It's not allowed to produce to `__consumer_offsets` in destination cluster, and uReplicator is using the new producer. Generally it's not a good idea to modify the internal topic yourself, however, if you want to do that, there is a `--topic.mappings` option in worker that you can copy `__consumer_offsets` in source Kafka cluster to a different topic in destination cluster. You can refer to the example here: https://github.com/uber/uReplicator/blob/master/config/topicmapping.properties
