### ISSUE TITLE
Can't package master

### ISSUE THREAD

**Issue by msestak** [uber/uReplicator#102]
Hi,

when I run mvn package clean -DskipTests I get this error:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] uReplicator ........................................ SUCCESS [  1.157 s]
[INFO] uReplicator-Controller ............................. SUCCESS [ 14.772 s]
[INFO] uReplicator-Worker ................................. SUCCESS [ 25.987 s]
[INFO] uReplicator-Distribution ........................... FAILURE [  2.380 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.524 s
[INFO] Finished at: 2017-12-12T11:52:47+01:00
[INFO] Final Memory: 231M/1095M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project uReplicator-Distribution: Could not resolve dependencies for project com.uber.uReplicator:uReplicator-Distribution:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Could not find artifact com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in maven-restlet (http://maven.restlet.org) -> [Help 1]
...

**Comment by xhl1988** [comment]
Could you please try it again? Current master works on my side.

**Comment by msestak** [comment]
Nope failed again.
[INFO] Reactor Summary:
[INFO] 
[INFO] uReplicator ........................................ SUCCESS [  0.287 s]
[INFO] uReplicator-Controller ............................. SUCCESS [ 15.531 s]
[INFO] uReplicator-Worker ................................. SUCCESS [ 25.390 s]
[INFO] uReplicator-Distribution ........................... FAILURE [  0.075 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.474 s
[INFO] Finished at: 2017-12-15T10:34:49+01:00
[INFO] Final Memory: 57M/963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project uReplicator-Distribution: Could not resolve dependencies for project com.uber.uReplicator:uReplicator-Distribution:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project uReplicator-Distribution: Could not resolve dependencies for project com.uber.uReplicator:uReplicator-Distribution:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.uber.uReplicator:uReplicator-Distribution:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:212)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT, com.uber.uReplicator:uReplicator-Worker:jar:1.0.3-SNAPSHOT: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT in http://maven.restlet.org was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:233)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :uReplicator-Distribution

**Comment by balboah** [comment]
if it's of any help, I've solved this issue when building my docker: https://github.com/uber/uReplicator/pull/104
also available at balboah/ureplicator from docker hub.

**Comment by xhl1988** [comment]
@msestak Does @balboah's solution work for you?
