### ISSUE TITLE
Mirroring is not working --> kafka.consumer.ConsumerTimeoutException

### ISSUE THREAD

**Issue by bigo86** [uber/uReplicator#133]
Hello everbody,
I'm new to uReplicator and I evaluate it for production use to subsitute MirrorMaker because of rebalancing issues and stability.
But at the moment I face always a kafka.consumer.ConsumerTimeoutException on worker, but I also see that worker is able to see the topics with current offsets. 
Do you have any idea?

We have 2 x Kafka Cluster (1.0.x) - 4 Brokers, 3 Zookeepers per Cluster.
I try to mirror all topics (exluded __consumer_offsets).
On a dedicated VM I have run the controller as well as worker and a local zookeeper like follows:

Cluster  A  - source
zk1-a.<domain>:2181

Cluster B - <destination>
zk1-b.<domain>:2181

HelixCluster
localhost:2181

I start controller like this:
```
startMirrorMakerController -helixClusterName testMirrorMaker -zookeeper localhost:2181 -port 9000 -mode auto -srcKafkaZkPath zk1-a.<domain>:2181 -destKafkaZkPath zk1-b.<domain>:2181 -enableAutoWhitelist true -patternToExcludeTopics __consumer_offsets -autoRebalanceDelayInSeconds 120 backUpToGit false -localBackupFilePath <backuplocation>
```

worker:
```
 startMirrorMakerWorker --consumer.config config/consumer.properties \
                         --producer.config config/producer.properties \
                         --helix.config config/helix.properties 
```

consumer.properties
```
zookeeper.connect=zk1-b.<domain>:2181 
# timeout in ms for connecting to zookeeper
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000
#consumer group id
group.id=kloak-mirrormaker-test
consumer.id=ureplicator-test-1
partition.assignment.strategy=roundrobin
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=8388608
queued.max.message.chunks=5
#consumer timeout
#consumer.timeout.ms=5000
auto.offset.reset=smallest
```

helix.properties
````
 zkServer=localhost:2181
 instanceId=testHelixMirrorMaker01
 helixClusterName=testMirrorMaker
````

worker log snipped:
```
018-06-19T10:28:59.440+0000: Total time for which application threads were stopped: 0.0005307 seconds, Stopping threads took: 0.0000787 seconds
[2018-06-19 10:28:59,439] INFO Reconnect due to error: (kafka.consumer.SimpleConsumer:78)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
	at kafka.mirrormaker.CompactConsumerFetcherThread.processFetchRequest(CompactConsumerFetcherThread.scala:209)
	at kafka.mirrormaker.CompactConsumerFetcherThread.doWork(CompactConsumerFetcherThread.scala:192)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
kafka.consumer.ConsumerTimeoutException
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:69)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread.run(MirrorMakerWorker.scala:288)
2018-06-19T10:28:59.717+0000: Total time for which application threads were stopped: 0.0006099 seconds, Stopping threads took: 0.0000932 seconds
[2018-06-19 10:28:59,716] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-06-19 10:28:59,717] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
kafka.consumer.ConsumerTimeoutException
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:69)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread.run(MirrorMakerWorker.scala:288)
kafka.consumer.ConsumerTimeoutException
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:69)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread.run(MirrorMakerWorker.scala:288)

```

**Comment by xhl1988** [comment]
@bigo86 Do you see any error logs on broker side?

**Comment by darshanmehta10** [comment]
@bigo86 Were you able to fix the issue? I am using similar setup and getting exactly the same error message.

**Comment by xhl1988** [comment]
@darshanmehta10 this error is due to no message to consume from src cluster, not a real error.
