### ISSUE TITLE
A general question

### ISSUE THREAD

**Issue by afa2001** [uber/uReplicator#148]
One question:

uReplicator is up and running and replicating from Kafka cluster A to cluster B; along the way, the worker thread crashes with the below error. Hence message afterwards are not replicated.
Now if I restart the worker thread, will it know  from which offset of cluster A to re-work on? Will destination cluster eventually have the fully replicated copy though restart is performed along the way?

[2018-08-15 08:20:03,483] ERROR Error when sending message to topic ecs-docker2 with key: null, value: 857 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback:47)
java.lang.IllegalStateException: Producer is closed forcefully.
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:522)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortIncompleteBatches(RecordAccumulator.java:502)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:147)
	at java.lang.Thread.run(Thread.java:748)
[2018-08-15 08:20:03,484] INFO Closing producer due to send failure. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-15 08:20:03,484] INFO Closing the Kafka producer with timeoutMillis = 0 ms. (org.apache.kafka.clients.producer.KafkaProducer:689)
[2018-08-15 08:20:03,484] INFO Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms. (org.apache.kafka.clients.producer.KafkaProducer:713)
[2018-08-15 08:20:03,484] INFO Exiting on send failure, skip committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-15 08:20:03,484] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-15 08:20:03,484] INFO Exiting on send failure, skip committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-15 08:20:03,484] INFO [mirrormaker-thread-dhHelixMirrorMaker01] Mirror maker thread stopped (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:70)
[2018-08-15 08:20:03,485] FATAL [mirrormaker-thread-dhHelixMirrorMaker01] Mirror maker thread exited abnormally, stopping the whole mirror maker. (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:112)

**Comment by xhl1988** [comment]
Yes, worker will commit consumed offset only after receiving successful callback after flushing the producer. If worker cashed, it will consume from last committed offset. So it can guarantee no data loss.

Regarding your error, you need to find the first produce error and see what happens. The log you pasted here is the result of closed producer. You can search for `Closing producer due to send failure.` in your log and see what is the error before that log. From my experience, the most common error is like: 1. message size bigger than destination broker config. 2. no enough replica if you want at-least-once delivery.

**Comment by afa2001** [comment]
@xhl1988 thanks for the information, but it seems worker is resending from the beginning, rather than the last offset. Is it due to the below configured in my consumer.properties?
auto.offset.reset=smallest

Below is my full config for consumer.properties
-----------------------------------------------------------
zookeeper.connect=10.35.226.84:2181/cluster1

# timeout in ms for connecting to zookeeper
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000

#consumer group id
group.id=dealhub-mirrormaker

consumer.id=dealhub-replicate-01
partition.assignment.strategy=roundrobin
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=8388608
queued.max.message.chunks=5

#consumer timeout
#consumer.timeout.ms=5000

auto.offset.reset=smallest
----------------------------------------------------------------

**Comment by xhl1988** [comment]
Did your worker ever successfully flush?
Or you can check your zookeeper and check if there is committed offset exist.

**Comment by afa2001** [comment]
@xhl1988 
It seems the consumer of ureplicator worker never update/commit the offset? or is it stored at Kafka rather than zookeeper?
I can see data is replicated over to destination cluster, however, the below command always shows the same offset for Zookeeper at source cluster...
get /consumers/dealhub-mirrormaker/offsets/cross-region/0
10011
cZxid = 0x1fb
ctime = Thu Aug 16 06:23:45 UTC 2018
mZxid = 0x4b8
mtime = Fri Aug 17 05:24:14 UTC 2018
pZxid = 0x1fb
cversion = 0
dataVersion = 4
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 5
numChildren = 0

**Comment by afa2001** [comment]
it's observed that the worker shutdown with the below, what does it mean? Timeout from zookeeper? Thanks.

[2018-08-17 09:42:28,646] INFO [CompactConsumerFetcherThread-dealhub-mirrormaker_dealhub-replicate-01-0-0], Topic partitions dump in fetcher thread: ArrayBuffer([[summary-markers2,0], Offset 0] , [[cross-region,0], Offset 0] , [[zhao,0], Offset 50050] , [[ecs-docker2,0], Offset 0] ) (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2018-08-17 09:42:52,810] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:42:52,810] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:43:52,820] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:43:52,820] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:44:52,834] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:44:52,835] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:45:52,842] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:45:52,846] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:46:52,853] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:46:52,854] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:47:28,823] INFO [CompactConsumerFetcherThread-dealhub-mirrormaker_dealhub-replicate-01-0-0], Topic partitions dump in fetcher thread: ArrayBuffer([[summary-markers2,0], Offset 0] , [[cross-region,0], Offset 0] , [[zhao,0], Offset 50050] , [[ecs-docker2,0], Offset 0] ) (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2018-08-17 09:47:52,859] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:47:52,860] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:48:52,869] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:48:52,869] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:30,566] INFO Start clean shutdown. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:30,567] INFO Shutting down consumer thread. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:30,567] INFO [mirrormaker-thread-dhHelixMirrorMaker01] mirrormaker-thread-dhHelixMirrorMaker01 shutting down (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:70)
[2018-08-17 09:49:32,875] INFO [mirrormaker-thread-dhHelixMirrorMaker01] Mirror maker thread shutdown complete (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:70)
[2018-08-17 09:49:32,876] INFO [mirrormaker-thread-dhHelixMirrorMaker01] Mirror maker thread stopped (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:70)
[2018-08-17 09:49:32,875] INFO [mirrormaker-thread-dhHelixMirrorMaker01] Mirror maker thread shutdown complete (kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread:70)
[2018-08-17 09:49:32,878] INFO Flushing last batches and commit offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,878] INFO Flushing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,879] INFO Committing offsets. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,880] INFO Shutting down consumer connectors. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,881] INFO Connector is now shutting down ! (kafka.mirrormaker.KafkaConnector:70)
[2018-08-17 09:49:32,892] INFO [CompactConsumerFetcherManager-1534498647615] Stopping leader finder thread (kafka.mirrormaker.CompactConsumerFetcherManager:70)
[2018-08-17 09:49:32,896] INFO [dealhub-mirrormaker_dealhub-replicate-01-leader-finder-thread], Shutting down (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread:70)
[2018-08-17 09:49:32,897] INFO [dealhub-mirrormaker_dealhub-replicate-01-leader-finder-thread], Stopped  (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread:70)
[2018-08-17 09:49:32,898] INFO [dealhub-mirrormaker_dealhub-replicate-01-leader-finder-thread], Shutdown completed (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread:70)
[2018-08-17 09:49:32,899] INFO [CompactConsumerFetcherManager-1534498647615] Stopping all fetchers (kafka.mirrormaker.CompactConsumerFetcherManager:70)
[2018-08-17 09:49:32,900] INFO [CompactConsumerFetcherThread-dealhub-mirrormaker_dealhub-replicate-01-0-0], Shutting down (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2018-08-17 09:49:32,900] INFO [CompactConsumerFetcherThread-dealhub-mirrormaker_dealhub-replicate-01-0-0], Stopped  (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2018-08-17 09:49:32,901] INFO [CompactConsumerFetcherThread-dealhub-mirrormaker_dealhub-replicate-01-0-0], Shutdown completed (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2018-08-17 09:49:32,902] INFO [CompactConsumerFetcherManager-1534498647615] All connections stopped (kafka.mirrormaker.CompactConsumerFetcherManager:70)
[2018-08-17 09:49:32,902] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread:82)
[2018-08-17 09:49:32,906] INFO EventThread shut down (org.apache.zookeeper.ClientCnxn:512)
[2018-08-17 09:49:32,906] INFO Session: 0x1653cd517820112 closed (org.apache.zookeeper.ZooKeeper:684)
[2018-08-17 09:49:32,907] INFO Closing producer. (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,907] INFO Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer:689)
[2018-08-17 09:49:32,913] INFO Is shutting down; call super.disconnect() (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,913] INFO disconnect dhHelixMirrorMaker01(PARTICIPANT) from testMirrorMaker (org.apache.helix.manager.zk.ZKHelixManager:547)
[2018-08-17 09:49:32,914] INFO Stop ParticipantHealthReportTimerTask (org.apache.helix.healthcheck.ParticipantHealthReportTask:63)
[2018-08-17 09:49:32,914] INFO Shutting down HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor:805)
[2018-08-17 09:49:32,914] INFO Reset HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor:520)
[2018-08-17 09:49:32,915] INFO Unregistering ClusterStatus: cluster=testMirrorMaker,messageQueue=dhHelixMirrorMaker01 (org.apache.helix.monitoring.mbeans.MessageQueueMonitor:106)
[2018-08-17 09:49:32,916] INFO Reset exectuor for msgType: TASK_REPLY, pool: java.util.concurrent.ThreadPoolExecutor@2177849e[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] (org.apache.helix.messaging.handling.HelixTaskExecutor:530)
[2018-08-17 09:49:32,916] INFO Shutting down pool: java.util.concurrent.ThreadPoolExecutor@2177849e[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] (org.apache.helix.messaging.handling.HelixTaskExecutor:474)
[2018-08-17 09:49:32,916] INFO Reset exectuor for msgType: STATE_TRANSITION, pool: java.util.concurrent.ThreadPoolExecutor@229c6181[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 4] (org.apache.helix.messaging.handling.HelixTaskExecutor:530)
[2018-08-17 09:49:32,916] INFO Shutting down pool: java.util.concurrent.ThreadPoolExecutor@229c6181[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 4] (org.apache.helix.messaging.handling.HelixTaskExecutor:474)
[2018-08-17 09:49:32,917] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,920] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,921] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,921] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,921] INFO Registering bean: ParticipantName=dhHelixMirrorMaker01 (org.apache.helix.monitoring.ParticipantStatusMonitor:109)
[2018-08-17 09:49:32,924] INFO Registering bean: Cluster=testMirrorMaker,Resource=zhao,Transition=OFFLINE--ONLINE (org.apache.helix.monitoring.ParticipantStatusMonitor:109)
[2018-08-17 09:49:32,924] INFO Registering bean: Cluster=testMirrorMaker,Resource=ecs-docker2,Transition=OFFLINE--ONLINE (org.apache.helix.monitoring.ParticipantStatusMonitor:109)
[2018-08-17 09:49:32,925] INFO Registering bean: Cluster=testMirrorMaker,Resource=summary-markers2,Transition=OFFLINE--ONLINE (org.apache.helix.monitoring.ParticipantStatusMonitor:109)
[2018-08-17 09:49:32,925] INFO Registering bean: Cluster=testMirrorMaker,Resource=cross-region,Transition=OFFLINE--ONLINE (org.apache.helix.monitoring.ParticipantStatusMonitor:109)
[2018-08-17 09:49:32,925] INFO Shutdown HelixTaskExecutor finished (org.apache.helix.messaging.handling.HelixTaskExecutor:810)
[2018-08-17 09:49:32,925] INFO 9 START:INVOKE /testMirrorMaker/INSTANCES/dhHelixMirrorMaker01/MESSAGES listener:org.apache.helix.messaging.handling.HelixTaskExecutor (org.apache.helix.manager.zk.CallbackHandler:194)
[2018-08-17 09:49:32,926] INFO dhHelixMirrorMaker01 unsubscribe child-change. path: /testMirrorMaker/INSTANCES/dhHelixMirrorMaker01/MESSAGES, listener: org.apache.helix.messaging.handling.HelixTaskExecutor@6e6f2380 (org.apache.helix.manager.zk.CallbackHandler:278)
[2018-08-17 09:49:32,926] INFO Subcribing to path:/testMirrorMaker/INSTANCES/dhHelixMirrorMaker01/MESSAGES took:0 (org.apache.helix.manager.zk.CallbackHandler:356)
[2018-08-17 09:49:32,928] INFO Reset HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor:520)
[2018-08-17 09:49:32,928] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,929] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,929] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,929] WARN Default reset method invoked. Either because the process longer own this resource or session timedout (org.apache.helix.participant.statemachine.StateModel:67)
[2018-08-17 09:49:32,929] INFO 9 END:INVOKE /testMirrorMaker/INSTANCES/dhHelixMirrorMaker01/MESSAGES listener:org.apache.helix.messaging.handling.HelixTaskExecutor Took: 4ms (org.apache.helix.manager.zk.CallbackHandler:266)
[2018-08-17 09:49:32,930] INFO reset handler: /testMirrorMaker/INSTANCES/dhHelixMirrorMaker01/MESSAGES, org.apache.helix.messaging.handling.HelixTaskExecutor@6e6f2380 (org.apache.helix.manager.zk.ZKHelixManager:774)
[2018-08-17 09:49:32,934] INFO Closing zkclient: State:CONNECTED Timeout:30000 sessionid:0x1653cd517820113 local:/172.17.0.2:50796 remoteserver:10.35.226.84/10.35.226.84:2181 lastZxid:2368 xid:244 sent:316 recv:321 queuedpkts:0 pendingresp:0 queuedevents:0 (org.apache.helix.manager.zk.ZkClient:141)
[2018-08-17 09:49:32,934] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread:82)
[2018-08-17 09:49:32,937] INFO EventThread shut down (org.apache.zookeeper.ClientCnxn:512)
[2018-08-17 09:49:32,940] INFO Session: 0x1653cd517820113 closed (org.apache.zookeeper.ZooKeeper:684)
[2018-08-17 09:49:32,941] INFO Closed zkclient (org.apache.helix.manager.zk.ZkClient:167)
[2018-08-17 09:49:32,941] INFO Cluster manager: dhHelixMirrorMaker01 disconnected (org.apache.helix.manager.zk.ZKHelixManager:588)
[2018-08-17 09:49:32,941] INFO helix connection shutdown successfully (kafka.mirrormaker.MirrorMakerWorker:70)
[2018-08-17 09:49:32,942] INFO Kafka mirror maker shutdown successfully (kafka.mirrormaker.MirrorMakerWorker:70)

**Comment by xhl1988** [comment]
The offset commit interval is set by --offset.commit.interval.ms <>, default is 1min.

For the log above, I saw it commit multiple times. Did the mtime changed accordingly?
During those several commits, did the worker keep producing to destination?

The timeout is due to Helix zookeeper, not related to source zookeeper.

**Comment by afa2001** [comment]
@xhl1988, thanks for the parameter --offset.commit.interval.ms, i'll try it out soon.

As of multiple commit you saw in the log file, i think it's written to log every 1 minute, even if sometimes there is nothing to replicate. I've observed mtime updates accordingly when there is data changes.

Question about the examples provided:

Let's say,  for a Production and DR configure (large latency - 150mili-second is expected between Production and DR)

Let's say, having 1 Kafka (kafka1) and 1 zookeeper server (zookeeper1) in production; 1 kafka (kafka2) and 1 zookeeper server (zookeeper2) in DR,

from the example, it seems the configuration is like: kafka1 (in production) is connecting to "zookeeper1:2181/cluster1", and kafka2 (in DR) is connecting to "zookeeper1:2181/cluster2",  what's the idea of having kafka2 in DR connects to zookeeper1 in prod? Probably i don't even need zookeeper2 in this scenario?  What's the good practice for this scenario? Thanks.

**Comment by afa2001** [comment]
Also, in case of multiple zookeepers, what's the way to specify it? I separated by comma, but it's not processed correctly.

[2018-08-23 01:55:33,222] INFO Trying to start MirrorMaker Controller with args: [startMirrorMakerController, -port, 9002, -zookeeper, 10.35.226.71:2181,, 10.35.226.150:2181, -helixClusterName, testMirrorMaker, -srcKafkaZkPath, 10.35.226.71:2181/cluster1,, 10.35.226.150:2181/cluster1, -destKafkaZkPath, 10.35.226.71:2181/cluster2,, 10.35.226.150:2181/cluster2, -autoRebalanceDelayInSeconds, 120, -localBackupFilePath, /var/log/kafka-mirror-maker-controller, -refreshTimeInSeconds, 20, -enableAutoWhitelist, true, -enableAutoTopicExpansion, true] (com.uber.stream.kafka.mirrormaker.starter.MirrorMakerStarter:38)
[2018-08-23 01:55:33,355] INFO Trying to init ControllerStarter with config:
{
        controller.helix.cluster.name : testMirrorMaker
        controller.zk.str : 10.35.226.71:2181,
        controller.port : 9002
        controller.mode : auto
        controller.instance.id : 0e64bfcd8e3c
        controller.environment : env
        controller.graphite.port : 0
        controller.enable.auto.whitelist : true
        controller.enable.auto.topic.expansion : true
        controller.pattern.exclude.topics : __consumer_offsets
        controller.srckafka.zkStr : 10.35.226.71:2181/cluster1,
        controller.destkafka.zkStr : 10.35.226.71:2181/cluster2,
----------------------------------------------------------------------------------------------

The same for putting multiple zookeeper addresses for zkServer in helix.properties
[2018-08-23 01:55:36,769] ERROR fail to connect dhHelixMirrorMaker01 (org.apache.helix.manager.zk.ZKHelixManager:534)
org.I0Itec.zkclient.exception.ZkException: Unable to connect to 10.35.226.71:2181, 10.35.226.150:2181

**Comment by xhl1988** [comment]
Zookeeper is just for Kafka cluster, it doesn't matter Kafka1 and Kafka2 shares the same zookeeper (of course, you need different root node).
The format for zookeeper is: `-zookeeper 10.35.226.71:2181,10.35.226.150:2181/<root>`, can you try using a root node?

**Comment by afa2001** [comment]
Sorry, not really catch it.

let's say, a set of kafka1 + zookeeper1 is in prod, another set of kafka2 + zookeeper2 is in DR environment. How to set the value of zkServer in helix.properties file for uReplicator?

**Comment by xhl1988** [comment]
zkServer in helix.properties is not related to Kafka zookeeper. zkServer in helix.properties is for Apache Helix, which should be the same as -zookeeper in controller start command.
