### ISSUE TITLE
Controller not exposing the API Endpoint

### ISSUE THREAD

**Issue by darshanmehta10** [uber/uReplicator#178]
I am running the controller docker image with the following command:

```
docker run -it -p 9000:9000 --expose=9000 \
my_repo/ureplicator:latest "controller" "startMirrorMakerController" \
-mode auto -enableAutoWhitelist true backUpToGit false \
-enableAutoTopicExpansion true -port 9000 -refreshTimeInSeconds 10 \
-srcKafkaZkPath localhost:2181 -zookeeper locahost:2181 \
-helixClusterName helix-dev
```

It starts up but I see the following Exception in the logs:

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:50)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:443)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:67)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1116)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:147)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:122)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:89)
	at com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver.<init>(KafkaBrokerTopicObserver.java:73)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.getAutoTopicWhitelistingManager(ControllerStarter.java:105)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.<init>(ControllerStarter.java:72)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.init(ControllerStarter.java:243)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.main(ControllerStarter.java:256)
	at com.uber.stream.kafka.mirrormaker.starter.MirrorMakerStarter.main(MirrorMakerStarter.java:39)
```

It still starts up, and prints the number of topics it's serving. However, when I try `curl http://localhost:9000/topics`, I get empty response. So, a couple of questions:

* Does the Exception mean it won't be able to replicate? 
* Do I need to pass any config to expose the REST endpoint? It should be exposing the endpoint if it's able to start.

**Comment by xhl1988** [comment]
The exception above might be due to 
1. `-srcKafkaZkPath localhost:2181`, is that a broker cluster root directory?
or 2. you missed `-dstKafkaZkPath` as it is required when enableAutoWhitelist is true.

Since you didn't pass `-dstKafkaZkPath`, it won't be able to auto whitelist any topics. otherwise, `curl http://localhost:9000/topics` should return topic names.
