### ISSUE TITLE
Worker stops with message - Zookeeper namespace does not exist

### ISSUE THREAD

**Issue by motonisar** [uber/uReplicator#245]
Hi All ,

I am trying to setup uReplicator on my local machine which is replicating data between two different clusters. My worker currently stops with error - Zookeeper namespace does not exist. The replication doesn't happen either, I go the same error while trying to runReplicator on of the cluster servers as well. I am following the steps listed here to setup the Replicator.
uber replicator configuration for the test environment. #223

help:
====
kindly take a look and please  me with this issue of what I am doing wrong and please let me know if I need to provide additional details - @yangy0000 , @xhl1988 

Below is the list of my config:
I am running a zookeeper on my local machine which comes bundled with Apache Kafka for the helix cluster.

Controller:
========
./start-controller.sh -port 9000 -helixClusterName uReplicatorDev -refreshTimeInSeconds 10 -enableAutoWhitelist true srcKafkaZkPath ZK1:2181,Zk2:2181,zk3:2181 -destKafkaZkPath zk4:2181,zk5:2181,zk6:2181 -zookeeper localhost:2181

Worker:
=======
./start-worker.sh --consumer.config /Users/Github/uReplicator-master/config/consumer.properties --producer.config /Users/Github/uReplicator-master/config/producer.properties --helix.config /Users/Github/uReplicator-master/config/helix.properties

helix properties:
==============
zkServer=localhost:2181
instanceId=uReplicatorDev01
helixClusterName=uReplicatorDev
#federated.deployment.name=uReplicator-Tests
enableAutowhitelist=true
port=9000
srckafkaZkpath=zk1:2181,zk2:2181,zk3:2181
destKafkaZkpath=zk4:2181,zk5:2181,zk6:2181

Producer properties:
================
bootstrap.servers=zk4.a:9093,zk5.b:9093,zk6.b:9093
security.protocol=SSL
ssl.truststore.location=/Users/apps/ssl/kafka.truststore.jks
ssl.truststore.password=REDACTED
ssl.keystore.location=/Users/apps/ssl/kafkaclient.keystore.jks
ssl.keystore.password= REDACTED
client.id=kloak-mirrormaker-test
producer.type=async
compression.type=none
 message encoder
key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
batch.size=262144
linger.ms=1000
buffer.memory=167772160
max.request.size=31457280
send.buffer.bytes=62914560
max.in.flight.requests.per.connection=5
delivery.timeout.ms=600000
request.timeout.ms=30000

Consumer properties:
================
zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/cluster1
bootstrap.servers=zk1.a.9093,zk2.b:9093,zk3.c:9093
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000
security.protocol=SSL
ssl.truststore.location=/Users/apps/ssl/azure/kafka.truststore.jks
ssl.truststore.password=REDACTED
ssl.keystore.location=/Users/apps/ssl/kafkaclient.keystore.jks
ssl.keystore.password= REDACTED
group.id=kloak-mirrormaker-test
consumer.id=kloakmms01-sjc1
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=8388608
queued.max.message.chunks=5
key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
#consumer timeout
#consumer.timeout.ms=5000
auto.offset.reset=smallest

Error log:
========
[2019-08-23 11:33:30,345] WARN [kloak-mirrormaker-test_kloakmms01-sjc1-leader-finder-thread]: Failed to find leader for Set(connect-offsets-13, connect-offsets-3, default_ksql_processing_log-0, connect-offsets-10, connect-status-1, connect-status-2, connect-status-0, connect-offsets-2, connect-offsets-19, connect-offsets-8, connect-offsets-5, connect-offsets-9, connect-offsets-21, connect-offsets-18, exampleTopic-0, __confluent.support.metrics-0, _schemas-0, connect-status-3, connect-status-4, connect-offsets-12, garytest-0, connect-offsets-14, connect-offsets-23, _confluent-ksql-default__command_topic-0, connect-offsets-7, connect-offsets-20, connect-offsets-24, connect-offsets-0, connect-offsets-22, connect-offsets-4, connect-offsets-17, test-0, connect-configs-0, connect-offsets-11, connect-offsets-16, connect-offsets-1, connect-offsets-6, connect-offsets-15, test1-0) (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread)
kafka.common.KafkaException: fetching topic metadata for topics [Set(test, default_ksql_processing_log, _schemas, test1, connect-configs, garytest, _confluent-ksql-default__command_topic, connect-status, connect-offsets, exampleTopic, __confluent.support.metrics)] from broker [List()] failed
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:77)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:98)
	at kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread.doWork(CompactConsumerFetcherManager.scala:350)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-08-23 11:33:30,345] INFO [CompactConsumerFetcherManager-1566574350136] Added fetcher for partitions ArrayBuffer() (kafka.mirrormaker.CompactConsumerFetcherManager)
2019-08-23T11:33:30.400+0500: Total time for which application threads were stopped: 0.0002453 seconds, Stopping threads took: 0.0000459 seconds
2019-08-23T11:33:30.492+0500: Total time for which application threads were stopped: 0.0002383 seconds, Stopping threads took: 0.0000413 seconds
[2019-08-23 11:33:30,491] INFO Flushing producer. (kafka.mirrormaker.WorkerInstance)
[2019-08-23 11:33:30,494] INFO Committing offsets. (kafka.mirrormaker.WorkerInstance)
org.apache.kafka.common.config.ConfigException: Zookeeper namespace does not exist
	at kafka.utils.ZkPath.checkNamespace(ZkUtils.scala:1012)
	at kafka.utils.ZkPath.createPersistent(ZkUtils.scala:1027)
	at kafka.utils.ZkUtils.createParentPath(ZkUtils.scala:458)
	at kafka.utils.ZkUtils.updatePersistentPath(ZkUtils.scala:533)
	at kafka.mirrormaker.KafkaConnector.commitOffsetToZooKeeper(KafkaConnector.scala:165)
	at kafka.mirrormaker.KafkaConnector$$anonfun$commitOffsets$1.apply(KafkaConnector.scala:157)
	at kafka.mirrormaker.KafkaConnector$$anonfun$commitOffsets$1.apply(KafkaConnector.scala:155)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at kafka.mirrormaker.KafkaConnector.commitOffsets(KafkaConnector.scala:155)
	at kafka.mirrormaker.WorkerInstance$$anonfun$maybeFlushAndCommitOffsets$3.apply$mcV$sp(WorkerInstance.scala:361)
	at kafka.mirrormaker.WorkerInstance$$anonfun$maybeFlushAndCommitOffsets$3.apply(WorkerInstance.scala:361)
	at kafka.mirrormaker.WorkerInstance$$anonfun$maybeFlushAndCommitOffsets$3.apply(WorkerInstance.scala:361)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.mirrormaker.WorkerInstance.maybeFlushAndCommitOffsets(WorkerInstance.scala:360)
	at kafka.mirrormaker.WorkerInstance$MirrorMakerThread.run(WorkerInstance.scala:459)
[2019-08-23 11:33:30,537] ERROR [mirrormaker-thread-uReplicatorDev01] Mirror maker thread failure due to  (kafka.mirrormaker.WorkerInstance$MirrorMakerThread)
org.apache.kafka.common.config.ConfigException: Zookeeper namespace does not exist
	at kafka.utils.ZkPath.checkNamespace(ZkUtils.scala:1012)
	at kafka.utils.ZkPath.createPersistent(ZkUtils.scala:1027)
	at kafka.utils.ZkUtils.createParentPath(ZkUtils.scala:458)
	at kafka.utils.ZkUtils.updatePersistentPath(ZkUtils.scala:533)
	at kafka.mirrormaker.KafkaConnector.commitOffsetToZooKeeper(KafkaConnector.scala:165)

**Comment by xhl1988** [comment]
uReplicator currently commit offset to Zookeeper. Do you have `consumer` node under
`zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/cluster1` ?

**Comment by motonisar** [comment]
I have the consumer nodes under this zookeeper: bootstrap.servers=zk1.a.9093,zk2.b:9093,zk3.c:9093
under zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/cluster1 ?

I was missing the zookeeper.connect=zk4:2181,zk5:2181,zk6:2181  in producer properties. when I added this I am getting the following error in the logs.

worker error logs:
=============
Error -> End point with security protocol PLAINTEXT not found for broker 0
	
[2019-08-23 14:42:08,517] INFO [CompactConsumerFetcherManager-1566585565766] Added fetcher for partitions ArrayBuffer() (kafka.mirrormaker.CompactConsumerFetcherManager)
[2019-08-23 14:42:08,721] INFO [kloak-mirrormaker-test_kloakmms01-sjc1-leader-finder-thread]: Partitions without leader Set(connect-offsets-13, connect-offsets-3, default_ksql_processing_log-0, connect-offsets-10, connect-status-1, connect-status-2, connect-status-0, connect-offsets-2, connect-offsets-19, connect-offsets-8, connect-offsets-5, connect-offsets-9, connect-offsets-21, connect-offsets-18, exampleTopic-0, __confluent.support.metrics-0, _schemas-0, connect-status-3, connect-status-4, connect-offsets-12, garytest-0, connect-offsets-14, connect-offsets-23, _confluent-ksql-default__command_topic-0, connect-offsets-7, connect-offsets-20, connect-offsets-24, connect-offsets-0, connect-offsets-22, connect-offsets-4, connect-offsets-17, test-0, connect-configs-0, connect-offsets-11, connect-offsets-16, connect-offsets-1, connect-offsets-6, connect-offsets-15, test1-0) (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread)
[2019-08-23 14:42:08,889] WARN [kloak-mirrormaker-test_kloakmms01-sjc1-leader-finder-thread]: Failed to find leader for Set(connect-offsets-13, connect-offsets-3, default_ksql_processing_log-0, connect-offsets-10, connect-status-1, connect-status-2, connect-status-0, connect-offsets-2, connect-offsets-19, connect-offsets-8, connect-offsets-5, connect-offsets-9, connect-offsets-21, connect-offsets-18, exampleTopic-0, __confluent.support.metrics-0, _schemas-0, connect-status-3, connect-status-4, connect-offsets-12, garytest-0, connect-offsets-14, connect-offsets-23, _confluent-ksql-default__command_topic-0, connect-offsets-7, connect-offsets-20, connect-offsets-24, connect-offsets-0, connect-offsets-22, connect-offsets-4, connect-offsets-17, test-0, connect-configs-0, connect-offsets-11, connect-offsets-16, connect-offsets-1, connect-offsets-6, connect-offsets-15, test1-0) (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread)
kafka.common.BrokerEndPointNotAvailableException: End point with security protocol PLAINTEXT not found for broker 0

controller logs:
===========
2019-08-23 15:07:01,854] ERROR For topic:__confluent.support.metrics, number of partitions for IdealState: __confluent.support.metrics, {IDEAL_STATE_MODE=CUSTOMIZED, MAX_PARTITIONS_PER_INSTANCE=1, NUM_PARTITIONS=1, REBALANCE_MODE=CUSTOMIZED, REPLICAS=1, STATE_MODEL_DEF_REF=OnlineOffline, STATE_MODEL_FACTORY_NAME=DEFAULT}{0={uReplicatorDev01=ONLINE}}{} doesn't match ExternalView: __confluent.support.metrics, {BUCKET_SIZE=0, IDEAL_STATE_MODE=CUSTOMIZED, MAX_PARTITIONS_PER_INSTANCE=1, NUM_PARTITIONS=1, REBALANCE_MODE=CUSTOMIZED, REPLICAS=1, STATE_MODEL_DEF_REF=OnlineOffline, STATE_MODEL_FACTORY_NAME=DEFAULT}{}{} (com.uber.stream.kafka.mirrormaker.controller.validation.ValidationManager:177)
[2019-08-23 15:07:01,855] WARN Got exception when removing metrics for externalView.topicPartitions.uReplicatorDev01.totalNumber (com.uber.stream.kafka.mirrormaker.controller.validation.ValidationManager:319)
java.lang.IllegalStateException: Not initialized yet
	at com.google.common.base.Preconditions.checkState(Preconditions.java:150)
	at com.uber.stream.ureplicator.common.KafkaUReplicatorMetricsReporter.get(KafkaUReplicatorMetricsReporter.java:176)
	at com.uber.stream.kafka.mirrormaker.controller.validation.ValidationManager.updatePerWorkerEVMetrics(ValidationManager.java:317)

**Comment by yangy0000** [comment]
are you testing against secured kafka?

**Comment by yangy0000** [comment]
For kafka with seurity feature, you might want to try the newly released worker. Starting command  `java -Dlog4j.configuration=file:config/test-log4j.properties -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=45 -verbose:gc -Xmx1g -Xms1g -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:gc-ureplicator-worker.log -server -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9089 -Dcom.sun.management.jmxremote.rmi.port=9089 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -cp uReplicator-Worker-3.0/target/uReplicator-Worker-3.0-2.0.0-SNAPSHOT-jar-with-dependencies.jar com.uber.stream.ureplicator.worker.WorkerStarter -federated_enabled false -consumer_config config/consumer.properties -producer_config config/producer.properties -helix_config config/helix.properties`

**Comment by motonisar** [comment]
I am using the current master branch.
