### ISSUE TITLE
 Not initialized yet

### ISSUE THREAD

**Issue by Technoboy-** [uber/uReplicator#254]
in federate mode:
 start a worker, and then shut it down without any task, it will throw the exception below。
 case 1 : ControllerWorkerHelixHandler is not initialized yet
 case 2:  KafkaUReplicatorMetricsReporter has shutdown hook , and it may disorder the shutdown logic
`
2019-09-11 18:01:54,762 INFO  [com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler#shutdown:112] : Shutting down MangerWorkerHelixManager
2019-09-11 18:01:54,767 INFO  [com.uber.stream.ureplicator.worker.WorkerInstance#cleanShutdown:218] : Start clean shutdown
2019-09-11 18:01:54,769 ERROR [com.uber.stream.ureplicator.worker.WorkerStarter#run:162] : Caught error during shutdown! 
java.lang.IllegalStateException: Not initialized yet
	at com.google.common.base.Preconditions.checkState(Preconditions.java:459)
	at com.uber.stream.ureplicator.common.KafkaUReplicatorMetricsReporter.checkState(KafkaUReplicatorMetricsReporter.java:200)
	at com.uber.stream.ureplicator.common.KafkaUReplicatorMetricsReporter.get(KafkaUReplicatorMetricsReporter.java:171)
	at com.uber.stream.ureplicator.worker.WorkerInstance.removeMetrics(WorkerInstance.java:384)
	at com.uber.stream.ureplicator.worker.WorkerInstance.cleanShutdown(WorkerInstance.java:252)
	at com.uber.stream.ureplicator.worker.WorkerInstance.cleanShutdown(WorkerInstance.java:209)
	at com.uber.stream.ureplicator.worker.WorkerStarter.shutdown(WorkerStarter.java:132)
	at com.uber.stream.ureplicator.worker.WorkerStarter$1.run(WorkerStarter.java:160)
`

**Comment by Technoboy-** [comment]
worker-3.0
