### ISSUE TITLE
manager does not close or shutdown the instance under the same manager instanceId in the cluster

### ISSUE THREAD

**Issue by Technoboy-** [uber/uReplicator#255]
`
2019-09-16 23:02:51,865 ERROR [org.apache.helix.controller.HelixControllerMain#startHelixController:175] : Exception while starting controller
org.apache.helix.HelixException: instance: manager1 already has a live-instance in cluster manager-worker-test-helix-with-manager
	at org.apache.helix.manager.zk.ParticipantManager.createLiveInstance(ParticipantManager.java:246)
	at org.apache.helix.manager.zk.ParticipantManager.handleNewSession(ParticipantManager.java:113)
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSessionAsParticipant(ZKHelixManager.java:1041)
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1015)
	at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:624)
	at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:662)
	at org.apache.helix.controller.HelixControllerMain.startHelixController(HelixControllerMain.java:170)
	at com.uber.stream.kafka.mirrormaker.common.utils.HelixSetupUtils.startHelixControllerInDistributeMode(HelixSetupUtils.java:107)
	at com.uber.stream.kafka.mirrormaker.common.utils.HelixSetupUtils.setup(HelixSetupUtils.java:55)
	at com.uber.stream.kafka.mirrormaker.manager.core.WorkerHelixManager.start(WorkerHelixManager.java:78)
	at com.uber.stream.kafka.mirrormaker.manager.core.ControllerHelixManager.start(ControllerHelixManager.java:150)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.start(ManagerStarter.java:84)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.main(ManagerStarter.java:142)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerBootstrap1.main(ManagerBootstrap1.java:66)
2019-09-16 23:02:51,865 ERROR [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#start:90] : Caught exception while starting uReplicator-Manager
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:327)
	at org.apache.helix.manager.zk.ZKHelixManager.getClusterManagmentTool(ZKHelixManager.java:803)
	at com.uber.stream.kafka.mirrormaker.manager.core.WorkerHelixManager.start(WorkerHelixManager.java:79)
	at com.uber.stream.kafka.mirrormaker.manager.core.ControllerHelixManager.start(ControllerHelixManager.java:150)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.start(ManagerStarter.java:84)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.main(ManagerStarter.java:142)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerBootstrap1.main(ManagerBootstrap1.java:66)
2019-09-16 23:02:51,865 ERROR [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#main:144] : Cannot start uReplicator-Manager: 
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:327)
	at org.apache.helix.manager.zk.ZKHelixManager.getClusterManagmentTool(ZKHelixManager.java:803)
	at com.uber.stream.kafka.mirrormaker.manager.core.WorkerHelixManager.start(WorkerHelixManager.java:79)
	at com.uber.stream.kafka.mirrormaker.manager.core.ControllerHelixManager.start(ControllerHelixManager.java:150)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.start(ManagerStarter.java:84)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.main(ManagerStarter.java:142)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerBootstrap1.main(ManagerBootstrap1.java:66)
2019-09-16 23:07:16,074 ERROR [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:186] : Failed to get topics from kafka zk: {}
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1001)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:673)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.refreshCache(KafkaBrokerTopicObserver.java:183)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.tryToRefreshCache(KafkaBrokerTopicObserver.java:222)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.access$000(KafkaBrokerTopicObserver.java:44)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver$1.run(KafkaBrokerTopicObserver.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1541)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1569)
	at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:120)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:680)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:991)
	... 13 more
2019-09-16 23:07:16,093 ERROR [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:186] : Failed to get topics from kafka zk: {}
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1001)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:673)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.refreshCache(KafkaBrokerTopicObserver.java:183)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.tryToRefreshCache(KafkaBrokerTopicObserver.java:222)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver.access$000(KafkaBrokerTopicObserver.java:44)
	at com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver$1.run(KafkaBrokerTopicObserver.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1541)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1569)
	at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:120)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:680)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:991)
	... 13 more
2019-09-16 23:08:54,615 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:195] : updating topic cache map for 0 new topics
2019-09-16 23:08:54,615 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:212] : Now serving 0 topics in Kafka cluster: cluster1
2019-09-16 23:09:11,206 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:195] : updating topic cache map for 0 new topics
2019-09-16 23:09:11,206 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#refreshCache:212] : Now serving 0 topics in Kafka cluster: cluster2
2019-09-16 23:13:36,867 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#handleChildChange:105] : starting to refresh topic list due to zk child change, currentChilds : [tboy1988]
2019-09-16 23:13:37,125 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#handleChildChange:128] : added 1 new topics to topic list in zk child change
2019-09-16 23:13:40,433 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#handleChildChange:105] : starting to refresh topic list due to zk child change, currentChilds : [tboy1988]
2019-09-16 23:13:40,434 INFO  [com.uber.stream.kafka.mirrormaker.common.core.KafkaBrokerTopicObserver#handleChildChange:128] : added 1 new topics to topic list in zk child change
2019-09-16 23:14:41,607 INFO  [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#stop:97] : Stopping src and dst kafka cluster validation manager
2019-09-16 23:14:41,607 INFO  [com.uber.stream.kafka.mirrormaker.manager.validation.KafkaClusterValidationManager#stop:57] : Stop KafkaBrokerTopicObserver
2019-09-16 23:14:41,607 INFO  [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#stop:99] : Stopping API component
2019-09-16 23:14:41,607 INFO  [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#stop:101] : Stopping helix manager
2019-09-16 23:14:41,607 INFO  [com.uber.stream.kafka.mirrormaker.manager.core.ControllerHelixManager#stop:173] : Trying to stop ManagerControllerHelix!
2019-09-16 23:14:41,608 INFO  [com.uber.stream.kafka.mirrormaker.manager.core.WorkerHelixManager#stop:97] : Trying to stop ManagerWorkerHelix!
2019-09-16 23:14:41,609 ERROR [com.uber.stream.kafka.mirrormaker.manager.ManagerStarter#stop:106] : Caught exception
java.lang.NullPointerException
	at com.uber.stream.kafka.mirrormaker.manager.core.ControllerHelixManager.stop(ControllerHelixManager.java:176)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.stop(ManagerStarter.java:102)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter$1.run(ManagerStarter.java:134)

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
`

**Comment by Technoboy-** [comment]
and the same with controller
