### ISSUE TITLE
mvn clear package error

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#258]
2019-09-17 15:49:50,438] ERROR Add instance to helix cluster failed. helixCluster: controller-worker-cluster1-cluster2-0 (com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler:95)
java.lang.RuntimeException: start mockWorker failed
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:47)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:73)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:92)
	at com.uber.stream.ureplicator.worker.WorkerInstance$$EnhancerByCGLIB$$1a81b093.start(<generated>)
	at com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler.start(ControllerWorkerHelixHandler.java:75)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.handleRouteAssignmentOnline(ManagerWorkerHelixHandler.java:189)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.onBecomeOnlineFromOffline(ManagerWorkerHelixHandler.java:124)
	at com.uber.stream.kafka.mirrormaker.common.core.OnlineOfflineStateFactory$OnlineOfflineStateModelHandler.onBecomeOnlineFromOffline(OnlineOfflineStateFactory.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:344)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:290)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:85)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2019-09-17 15:49:50,442] ERROR Start controllerWorkerHelixHandler failed (com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler:191)
java.lang.RuntimeException: start mockWorker failed
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:47)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:73)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:92)
	at com.uber.stream.ureplicator.worker.WorkerInstance$$EnhancerByCGLIB$$1a81b093.start(<generated>)
	at com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler.start(ControllerWorkerHelixHandler.java:75)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.handleRouteAssignmentOnline(ManagerWorkerHelixHandler.java:189)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.onBecomeOnlineFromOffline(ManagerWorkerHelixHandler.java:124)
	at com.uber.stream.kafka.mirrormaker.common.core.OnlineOfflineStateFactory$OnlineOfflineStateModelHandler.onBecomeOnlineFromOffline(OnlineOfflineStateFactory.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:344)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:290)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:85)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2019-09-17 15:49:50,443] INFO Shutting down ControllerWorkerHelixHandler (com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler:154)
[2019-09-17 15:49:50,444] INFO Shutdown ControllerWorkerHelixHandler finished (com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler:165)
[2019-09-17 15:49:50,445] ERROR Exception while executing a state transition task 0 (org.apache.helix.messaging.handling.HelixStateTransitionHandler:300)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:344)
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:290)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:85)
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: start mockWorker failed
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.handleRouteAssignmentOnline(ManagerWorkerHelixHandler.java:195)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.onBecomeOnlineFromOffline(ManagerWorkerHelixHandler.java:124)
	at com.uber.stream.kafka.mirrormaker.common.core.OnlineOfflineStateFactory$OnlineOfflineStateModelHandler.onBecomeOnlineFromOffline(OnlineOfflineStateFactory.java:55)
	... 12 more
Caused by: java.lang.RuntimeException: start mockWorker failed
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:47)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:73)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:92)
	at com.uber.stream.ureplicator.worker.WorkerInstance$$EnhancerByCGLIB$$1a81b093.start(<generated>)
	at com.uber.stream.ureplicator.worker.helix.ControllerWorkerHelixHandler.start(ControllerWorkerHelixHandler.java:75)
	at com.uber.stream.ureplicator.worker.helix.ManagerWorkerHelixHandler.handleRouteAssignmentOnline(ManagerWorkerHelixHandler.java:189)
	... 14 more

**Comment by Technoboy-** [comment]
rebuild with "mvn clean package -DskipTests=true"

**Comment by yangy0000** [comment]
The ERROR log you attached comes from unittest, which is expected sometimes. 
Are you attach the full log?  Also, as Technoboy- mentioned, you can try to rebuild with "mvn clean package -DskipTests=true" as well.
