### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/Graceful

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#264]
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/Graceful
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.restlet.engine.Engine.registerHelper(Engine.java:896)
	at org.restlet.engine.Engine.registerHelpers(Engine.java:928)
	at org.restlet.engine.Engine.registerHelpers(Engine.java:968)
	at org.restlet.engine.Engine.discoverConnectors(Engine.java:660)
	at org.restlet.engine.Engine.<init>(Engine.java:495)
	at org.restlet.engine.Engine.register(Engine.java:386)
	at org.restlet.engine.Engine.register(Engine.java:372)
	at org.restlet.engine.Engine.getInstance(Engine.java:256)
	at org.restlet.Restlet.<init>(Restlet.java:131)
	at org.restlet.Restlet.<init>(Restlet.java:108)
	at org.restlet.Component.<init>(Component.java:181)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.<init>(ManagerStarter.java:52)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.init(ManagerStarter.java:108)
	at com.uber.stream.kafka.mirrormaker.manager.ManagerStarter.main(ManagerStarter.java:119)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.Graceful
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

**Comment by Technoboy-** [comment]
it occurs at the start of manager/controller, but nothing affect.
try to resolve it with below updates:
`

<restlet.version>2.3.0</restlet.version>


<dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-util</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-io</artifactId>
      <version>${jetty.version}</version>
    </dependency>
`

**Comment by Bruce2jiang** [comment]
How is dependence the same?

**Comment by Bruce2jiang** [comment]
restlet  dependence ?

**Comment by Bruce2jiang** [comment]
error :

[2019-09-18 08:48:35,085] ERROR Error while executing task. 140666f5-53dc-441e-b4fb-4200e7de2c9a, {CREATE_TIMESTAMP=1568767714968, ClusterEventName=currentStateChange, EXE_SESSION_ID=100618caf1e000c, FROM_STATE=ONLINE, MSG_ID=140666f5-53dc-441e-b4fb-4200e7de2c9a, MSG_STATE=read, MSG_TYPE=STATE_TRANSITION, PARTITION_NAME=1, READ_TIMESTAMP=1568767715023, RESOURCE_NAME=testTopic1, SRC_NAME=KYE-1000676591, SRC_SESSION_ID=100618caf1e000a, STATE_MODEL_DEF=OnlineOffline, STATE_MODEL_FACTORY_NAME=DEFAULT, TGT_NAME=Server_localhost_1, TGT_SESSION_ID=100618caf1e000c, TO_STATE=OFFLINE}{}{} (org.apache.helix.messaging.handling.HelixTaskExecutor:395)
java.lang.NullPointerException
	at org.apache.helix.messaging.handling.HelixTaskExecutor.scheduleTask(HelixTaskExecutor.java:371)
	at org.apache.helix.messaging.handling.HelixTaskExecutor.onMessage(HelixTaskExecutor.java:777)
	at org.apache.helix.manager.zk.CallbackHandler.invoke(CallbackHandler.java:243)
	at org.apache.helix.manager.zk.CallbackHandler.enqueueTask(CallbackHandler.java:177)
	at org.apache.helix.manager.zk.CallbackHandler.handleChildChange(CallbackHandler.java:431)
	at org.I0Itec.zkclient.ZkClient$10.run(ZkClient.java:844)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)
[2019-09-18 08:48:35,086] INFO updating topic cache map for 0 new topics (com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver:168)

**Comment by yangy0000** [comment]
fixed on https://github.com/uber/uReplicator/pull/269
