### ISSUE TITLE
controller error 

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#267]
Invalid cluster setup, missing znode path: /manager-controller-testing-dc1/CONTROLLER/HISTORY
 (org.apache.helix.manager.zk.ZKUtil)
[2019-09-18 11:26:43,704] ERROR fail to createClient. (org.apache.helix.manager.zk.ZKHelixManager)
org.apache.helix.HelixException: Cluster structure is not set up for cluster: manager-controller-testing-dc1
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:861)
	at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:493)
	at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:531)
	at com.uber.stream.kafka.mirrormaker.controller.core.ManagerControllerHelix.start(ManagerControllerHelix.java:74)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.start(ControllerStarter.java:52)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.main(ControllerStarter.java:163)
[2019-09-18 11:26:43,705] ERROR fail to connect testHelixMirrorMaker01 (org.apache.helix.manager.zk.ZKHelixManager)
org.apache.helix.HelixException: Cluster structure is not set up for cluster: manager-controller-testing-dc1
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:861)
	at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:493)
	at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:531)
	at com.uber.stream.kafka.mirrormaker.controller.core.ManagerControllerHelix.start(ManagerControllerHelix.java:74)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.start(ControllerStarter.java:52)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.main(ControllerStarter.java:163)
[2019-09-18 11:26:43,706] INFO disconnect testHelixMirrorMaker01(PARTICIPANT) from manager-controller-testing-dc1 (org.apache.helix.manager.zk.ZKHelixManager)
[2019-09-18 11:26:43,706] WARN ParticipantHealthReportTimerTask already stopped (org.apache.helix.healthcheck.ParticipantHealthReportTask)
[2019-09-18 11:26:43,706] INFO Shutting down HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2019-09-18 11:26:43,706] INFO Reset HelixTaskExecutor (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2019-09-18 11:26:43,706] INFO Reset exectuor for msgType: TASK_REPLY, pool: java.util.concurrent.ThreadPoolExecutor@3ada9e37[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2019-09-18 11:26:43,706] INFO Shutting down pool: java.util.concurrent.ThreadPoolExecutor@3ada9e37[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2019-09-18 11:26:43,706] INFO Registering bean: ParticipantName=testHelixMirrorMaker01 (org.apache.helix.monitoring.ParticipantStatusMonitor)
[2019-09-18 11:26:43,707] INFO Shutdown HelixTaskExecutor finished (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2019-09-18 11:26:43,707] INFO Closing zkclient: State:CONNECTED Timeout:600000 sessionid:0x100a49a6372839a local:/10.121.18.15:4843 remoteserver:UAT-HADOOP-06/10.121.18.6:2181 lastZxid:94491587116 xid:15 sent:15 recv:15 queuedpkts:0 pendingresp:0 queuedevents:0 (org.apache.helix.manager.zk.ZkClient)
[2019-09-18 11:26:43,707] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2019-09-18 11:26:43,710] INFO Session: 0x100a49a6372839a closed (org.apache.zookeeper.ZooKeeper)
[2019-09-18 11:26:43,710] INFO Closed zkclient (org.apache.helix.manager.zk.ZkClient)
[2019-09-18 11:26:43,710] INFO EventThread shut down for session: 0x100a49a6372839a (org.apache.zookeeper.ClientCnxn)
[2019-09-18 11:26:43,710] INFO Cluster manager: testHelixMirrorMaker01 disconnected (org.apache.helix.manager.zk.ZKHelixManager)
[2019-09-18 11:26:43,710] ERROR Failed to start ManagerControllerHelix manager-controller-testing-dc1 (com.uber.stream.kafka.mirrormaker.controller.core.ManagerControllerHelix)
org.apache.helix.HelixException: Cluster structure is not set up for cluster: manager-controller-testing-dc1
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:861)
	at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:493)
	at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:531)
	at com.uber.stream.kafka.mirrormaker.controller.core.ManagerControllerHelix.start(ManagerControllerHelix.java:74)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.start(ControllerStarter.java:52)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.main(ControllerStarter.java:163)

**Comment by Technoboy-** [comment]
try to start manager first with config the same deploymentName -testing-dc1

**Comment by Bruce2jiang** [comment]
manager:-deployment testing-dc1 ,  controller: -deploymentName testing-dc1
