### ISSUE TITLE
master branch--Federation Mode can not process kafka replication nomally

### ISSUE THREAD

**Issue by shaolilanse** [uber/uReplicator#326]
Now，I use master branch to run Manager, Controller, Worker by Federation Mode, and they are running. When I produce  messages to kafka topic-sourceCluster， kafka topic-destination has no message. 

manage log: 
`[2021-01-13 17:56:49,038] INFO No live instances, do nothing! (com.uber.stream.kafka.mirrormaker.manager.core.ControllerLiveInstanceChangeListener)
[2021-01-13 17:57:47,727] WARN Unable to report to Graphite (com.codahale.metrics.graphite.GraphiteReporter)
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:244)
        at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
        at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:129)
        at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:265)
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
        at com.codahale.metrics.ScheduledReporter.lambda$start$0(ScheduledReporter.java:177)
        at com.codahale.metrics.ScheduledReporter$$Lambda$2/736709391.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

controller log:
`[2021-01-13 17:49:40,124] INFO testHelixMirrorMaker05 subscribes child-change. path: /manager-worker-testing-dc1/INSTANCES/testHelixMirrorMaker05/MESSAGES, listener: org.apache.helix.messaging.handling.HelixTaskExecutor@13a5fe33 (org.apache.helix.manager.zk.CallbackHandler)
[2021-01-13 17:49:40,125] INFO Subcribing to path:/manager-worker-testing-dc1/INSTANCES/testHelixMirrorMaker05/MESSAGES took:1 (org.apache.helix.manager.zk.CallbackHandler)
[2021-01-13 17:49:40,125] INFO No Messages to process (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2021-01-13 17:49:40,125] INFO 27 END:INVOKE /manager-worker-testing-dc1/INSTANCES/testHelixMirrorMaker05/MESSAGES listener:org.apache.helix.messaging.handling.HelixTaskExecutor Took: 1ms (org.apache.helix.manager.zk.CallbackHandler)`

worker log:
`[2021-01-13 17:49:40,125] INFO No Messages to process (org.apache.helix.messaging.handling.HelixTaskExecutor)
[2021-01-13 17:49:40,125] INFO 27 END:INVOKE /manager-worker-testing-dc1/INSTANCES/testHelixMirrorMaker05/MESSAGES listener:org.apache.helix.messaging.handling.HelixTaskExecutor Took: 1ms (org.apache.helix.manager.zk.CallbackHandler)`

And I run: curl -X GET "hdp25.bigdata.zll.360es.cn:9999/admin/worker_number_override", 
the result is :
`{"worker_number_override":{}}`

**Comment by auqf** [comment]
the start worker error of me is Error: Could not find or load main class kafka.mirrormaker.MirrorMakerWorker, how to resolve it?

**Comment by yangy0000** [comment]
Can you share the your startup command?

**Comment by shaolilanse** [comment]
Manager:
`java -Dlog4j.configuration=file:config/tools-log4j.properties -Xms3g -Xmx3g -Xmn512m -XX:NewSize=512m -XX:MaxNewSize=512m -XX:+AlwaysPreTouch -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+PrintCommandLineFlags -XX:CMSInitiatingOccupancyFraction=80 -XX:SurvivorRatio=2 -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCTimeStamps -Xloggc:/tmp/ureplicator-manager/gc-ureplicator-manager.log -server -cp uReplicator-Manager/target/uReplicator-Manager-1.0.0-SNAPSHOT-jar-with-dependencies.jar com.uber.stream.kafka.mirrormaker.manager.ManagerStarter -config config/clusters.properties -srcClusters cluster1,cluster2 -destClusters cluster3 -enableRebalance false -zookeeper zk1,zk2,zk3/ureplicator/testing-dc1 -managerPort <port> -deployment testing-dc1 -env dc1.testing-dc1 -instanceId <id> -controllerPort <port> -graphiteHost 127.0.0.1 -graphitePort 4756 -metricsPrefix ureplicator-manager -workloadRefreshPeriodInSeconds 300 -initMaxNumPartitionsPerRoute 1500 -maxNumPartitionsPerRoute 2000 -initMaxNumWorkersPerRoute 10 -maxNumWorkersPerRoute 80`

Controller:
`java -Dlog4j.configuration=file:config/tools-log4j.properties -Xms3g -Xmx3g -Xmn512m -XX:NewSize=512m -XX:MaxNewSize=512m -XX:+AlwaysPreTouch -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+PrintCommandLineFlags -XX:CMSInitiatingOccupancyFraction=80 -XX:SurvivorRatio=2 -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCTimeStamps -Xloggc:/tmp/ureplicator-controller/gc-ureplicator-controller.log -server -cp uReplicator-Controller/target/uReplicator-Controller-1.0.0-SNAPSHOT-jar-with-dependencies.jar com.uber.stream.kafka.mirrormaker.controller.ControllerStarter -config config/clusters.properties -srcClusters cluster1,cluster2 -destClusters cluster3 -enableFederated true -deploymentName testing-dc1 -mode customized -zookeeper zk1,zk2,zk3/ureplicator/testing-dc1 -port <port> -env dc1.testing-dc1 -instanceId <id> -hostname <hostname> -graphiteHost 127.0.0.1 -graphitePort 4756 -metricsPrefix ureplicator-controller -enableAutoWhitelist false -enableAutoTopicExpansion true -autoRebalanceDelayInSeconds 120 -autoRebalancePeriodInSeconds 120 -autoRebalanceMinIntervalInSeconds 600 -autoRebalanceMinLagTimeInSeconds 900 -autoRebalanceMinLagOffset 100000 -autoRebalanceMaxOffsetInfoValidInSeconds 1800 -autoRebalanceWorkloadRatioThreshold 1.5 -maxDedicatedLaggingInstancesRatio 0.2 -maxStuckPartitionMovements 3 -moveStuckPartitionAfterMinutes 20 -workloadRefreshPeriodInSeconds 300 -patternToExcludeTopics ^__.* -enableSrcKafkaValidation true -consumerCommitZkPath "" -maxWorkingInstances 0 -autoRebalanceDelayInSeconds 120 -refreshTimeInSeconds 600 -initWaitTimeInSeconds 120 -numOffsetThread 10 -blockingQueueSize 30000 -offsetRefreshIntervalInSec 300 -backUpToGit false -localBackupFilePath /tmp/ureplicator-controller -localGitRepoClonePath /ureplicator-controller-bkp `

Worker:
`java -Dlog4j.configuration=file:config/tools-log4j.properties -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=45 -verbose:gc -Xmx5g -Xms5g -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -server -javaagent:./bin/libs/jmxtrans-agent-1.2.4.jar=config/jmxtrans.xml -cp uReplicator-Worker/target/uReplicator-Worker-1.0.0-SNAPSHOT-jar-with-dependencies.jar kafka.mirrormaker.MirrorMakerWorker --cluster.config config/clusters.properties --consumer.config config/consumer.properties --producer.config config/producer.properties --helix.config config/helix.properties --dstzk.config config/dstzk.propertiess`

**Comment by yangy0000** [comment]
sorry, it looks like the doc is a bit outdated. there are two options :
1: use below command to startup worker
java -Dlog4j.configuration=file:config/test-log4j.properties -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=45 -verbose:gc -Xmx1g -Xms1g -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:gc-ureplicator-worker.log -server -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9089 -Dcom.sun.management.jmxremote.rmi.port=9089 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -cp uReplicator-Worker-3.0/target/uReplicator-Worker-3.0-2.0.1-SNAPSHOT-jar-with-dependencies.jar com.uber.stream.ureplicator.worker.WorkerStarter -federated_enabled true -consumer_config config/consumer.properties -producer_config config/producer.properties -helix_config config/helix.properties  -topic_partition_count_observer true -cluster_config config/clusters.properties

2: go to "release-1.0" branch and use your existing command.

**Comment by yangy0000** [comment]
in addition. docker-compose-example5.yml should able to bootstrap a federated ureplicator cluster in docker environment.
you can use command 
`curl -X POST "localhost:8100/topics/dummyTopic?src=cluster1&dst=cluster2"                                                                                                                        
`to add a topic into replication
