### ISSUE TITLE
Use docker run "work" error

### ISSUE THREAD

**Issue by kirin-13** [uber/uReplicator#333]
Start the "work" process using the official sample command.
```
docker run -d --link devenv:devenv --name worker ureplicator "worker" \
--consumer.config example/example-consumer.properties \
--producer.config example/example-producer.properties \
--helix.config example/example-helix.properties
```
But it gives an error when starting the "work" process.

error message.
```
[2021-02-26 03:23:36,888] INFO Start WorkerStarter with arguments --consumer.config (com.uber.stream.ureplicator.worker.WorkerStarter)
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --consumer.config
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:394)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:371)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.uber.stream.ureplicator.worker.WorkerStarter.main(WorkerStarter.java:144)
```

I checked the documentation and used the following command.

```
docker run -d --link devenv:devenv --name worker ureplicator "worker" \
-consumer_config example/example-consumer.properties \
-producer_config example/example-producer.properties \
-helix_config example/example-helix.properties
```
"Work" processes run normally, Is it a documentation error that is causing this problem (I tried to submit a PR to fix the issue, but I don't have permission to do so.).

**Comment by yangy0000** [comment]
sorry for the confusion, it's a documentation error, just fixe it
