### ISSUE TITLE
My destination kafka zookeeper can't be recognized ?

### ISSUE THREAD

**Issue by yyb345** [uber/uReplicator#36]
Now our source kafka cluster and  dest kafka cluster is already install and configured, 
my command line for uReplicator controller start is following:

./uReplicator-Distribution/target/uReplicator-Distribution-pkg/bin/start-controller.sh  -helixClusterName testMirrorMaker -zookeeper  XXX:2181 -port 9000 -mode auto -srcKafkaZkPath XXX:2181/violet –destKafkaZkPath XXX:2181/violet -enableAutoWhitelist true -autoRebalanceDelayInSeconds 120 -backUpToGit false -localBackupFilePath ~/backup_

**My destination kafka cluster zookeeper address is correct, but it is can not be recognized** 
error is following :
[2017-07-26 15:48:15,761] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient:641)
2017-07-26T15:48:15.859+0800: Total time for which application threads were stopped: 0.0002728 seconds, Stopping threads took: 0.0000203 seconds
[2017-07-26 15:48:15,961] ERROR Failed to register metrics to HelixKafkaMirrorMakerMetricsReporter java.lang.NullPointerException (com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver:93)
[2017-07-26 15:48:15,962] INFO Trying to init KafkaBrokerTopicObserver destKafkaCluster with ZK: null (com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver:70)
[2017-07-26 15:48:15,962] INFO Initiating client connection, connectString=null sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@3c9d0b9d (org.apache.zookeeper.ZooKeeper:438)
[2017-07-26 15:48:15,962] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread:64)
Exception in thread "main" java.lang.NullPointerException
	at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:50)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:443)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:67)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1116)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:147)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:122)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:89)
	at com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver.<init>(KafkaBrokerTopicObserver.java:73)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.getAutoTopicWhitelistingManager(ControllerStarter.java:106)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.<init>(ControllerStarter.java:73)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.init(ControllerStarter.java:244)
	at com.uber.stream.kafka.mirrormaker.controller.ControllerStarter.main(ControllerStarter.java:257)
	at com.uber.stream.kafka.mirrormaker.starter.MirrorMakerStarter.main(MirrorMakerStarter.java:42)

**Comment by xhl1988** [comment]
@yyb345 The option in your command is "–destKafkaZkPath" instead of "-destKafkaZkPath".

**Comment by yyb345** [comment]
Thanks, but  another error came up:
[2017-07-27 10:56:50,110] INFO Initiating client connection, connectString=xxx:2181/violet sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@370736d9 (org.apache.zookeeper.ZooKeeper:438)
[2017-07-27 10:56:50,138] INFO Opening socket connection to server xxx/xxx:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:975)
[2017-07-27 10:56:50,195] INFO Socket connection established to xxx/xxx:2181, initiating session (org.apache.zookeeper.ClientCnxn:852)
[2017-07-27 10:56:50,200] INFO Session establishment complete on server xxx/xxx:2181, sessionid = 0x35d0f2eb07fd2b9, negotiated timeout = 30000 (org.apache.zookeeper.ClientCnxn:1235)
[2017-07-27 10:56:50,202] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient:641)
2017-07-27T10:56:50.301+0800: Total time for which application threads were stopped: 0.0002783 seconds, Stopping threads took: 0.0000204 seconds
[2017-07-27 10:56:50,398] **ERROR Failed to register metrics to HelixKafkaMirrorMakerMetricsReporter java.lang.NullPointerException** (com.uber.stream.kafka.mirrormaker.controller.core.KafkaBrokerTopicObserver:93)

**Comment by xhl1988** [comment]
@yyb345 Have you tried the latest master branch? I think we fixed it in #30

**Comment by yyb345** [comment]
Not yet, but it would not  influence uReplicator controller's service, right?

**Comment by xhl1988** [comment]
No, it won't.
