### ISSUE TITLE
kafka version conflict ?

### ISSUE THREAD

**Issue by yyb345** [uber/uReplicator#37]
In my case, there are two clusters, source cluster named s1, dest cluster named d1
_**s1 setup :  kafka 0.8.2.1 version**_
d1 setup :kafka 0.10.2.1 version
When running uReplicator worker, our topics on s1 can not be copied to s2 , following is exceptions:

[2017-07-27 19:53:58,703] INFO Reconnect due to error: (kafka.consumer.SimpleConsumer:78)
**java.nio.channels.ClosedChannelException**
        at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85)
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
        at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
        at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
        at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
        at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
        at kafka.mirrormaker.CompactConsumerFetcherThread.processFetchRequest(CompactConsumerFetcherThread.scala:196)
        at kafka.mirrormaker.CompactConsumerFetcherThread.doWork(CompactConsumerFetcherThread.scala:188)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
[2017-07-27 19:53:58,706] WARN [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], Error in fetch Name: FetchRequest; Version: 3; CorrelationId: 2; ClientId: kloak-mirrormaker-test; ReplicaId: -1; MaxWait: 100 ms; MinBytes: 1 bytes; MaxBytes:2147483647 bytes; RequestInfo: ([druid-monitor-data,0],PartitionFetchInfo(1727231592,8388608)). Possible cause: java.io.EOFException (kafka.mirrormaker.CompactConsumerFetcherThread:85)
[2017-07-27 19:53:58,906] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], handling partitions with error for Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2017-07-27 19:53:58,907] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], enter removePartitions in CompactConsumerFetcherThread 39 for set Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:70)
[2017-07-27 19:53:58,907] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], Finish removePartitions in CompactConsumerFetcherThread 39 for set Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:70)

**I guess the reason maybe is  that 0.10.2.1 consumer's interface couldn't be compatible with 0.8.2.1 ? What's the possible solutions, uReplicator supports older kafka versions?**

**Comment by xhl1988** [comment]
Yes, 0.10.2.1 consumer doesn't work with 0.8.2.1 broker.
You can reset to 44a62e54b8d06905b304dab145b7bbff654cca27 which uses 0.8.2.1 consumer and 0.9.0.0 producer.
You might also want to apply the bug fix in #35

**Comment by yyb345** [comment]
I reset to 44a62e5, it's compatible with 0.8.2.1. Unfortunately，my topics still couldn't copied to dest cluster.  Following is exceptions:

[2017-07-28 11:09:01,702] WARN [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], **Error in fetch Name:** FetchRequest; Version: 1; CorrelationId: 181; ClientId: kloak-mirrormaker-test; ReplicaId: -1; MaxWait: 100 ms; MinBytes: 1 bytes; RequestInfo: [druid-monitor-data,0] -> PartitionFetchInfo(1727231592,8388608). **Possible cause: java.nio.BufferUnderflowException (kafka.mirrormaker.CompactConsumerFetcherThread:83)**
[2017-07-28 11:09:01,903] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], handling partitions with error for Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:68)
[2017-07-28 11:09:01,903] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], enter removePartitions in CompactConsumerFetcherThread 39 for set Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:68)
[2017-07-28 11:09:01,903] INFO [CompactConsumerFetcherThread-kloak-mirrormaker-test_kloakmms01-sjc1-0-2823], Finish removePartitions in CompactConsumerFetcherThread 39 for set Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherThread:68)
[2017-07-28 11:09:01,904] INFO [kloak-mirrormaker-test_kloakmms01-sjc1-leader-finder-thread], Partitions without leader Set([druid-monitor-data,0]) (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread:68)

**Comment by xhl1988** [comment]
@yyb345 My bad. 44a62e5 use 0.8.2.1 for controller and 0.9.0.0 for worker. So your consumer is still 0.9.0.0. You can change the version to 0.8.2.1 in uReplicator-Worker/pom.xml. It should be working then.

**Comment by yyb345** [comment]
When I  change the version to 0.8.2.1 in uReplicator-Worker/pom.xml, compiler doesn't works:

[INFO] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala: -1: info: compiling
[INFO] Compiling 6 source files to /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/target/classes at 1501214191900
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherManager.scala:24: error: object BrokerEndPoint is not a member of package kafka.cluster
[INFO] import kafka.cluster.{BrokerEndPoint, Cluster}
[INFO]        ^
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherManager.scala:29: error: object CoreUtils is not a member of package kafka.utils
[INFO] import kafka.utils.CoreUtils._
[INFO]                    ^
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherManager.scala:32: error: object SecurityProtocol is not a member of package org.apache.kafka.common.protocol
[INFO] import org.apache.kafka.common.protocol.SecurityProtocol
[INFO]        ^
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherThread.scala:27: error: object CoreUtils is not a member of package kafka.utils
[INFO] import kafka.utils.CoreUtils._
[INFO]                    ^
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherThread.scala:26: error: object PartitionFetchState is not a member of package kafka.server
[INFO] import kafka.server.{ClientIdTopicPartition, FetcherLagStats, FetcherStats, PartitionFetchState}
[INFO]        ^
[ERROR] /home/worker/uReplicator-revert-release-version-1.0.0/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherThread.scala:22: error: object BrokerEndPoint is not a member of package kafka.cluster

**Comment by xhl1988** [comment]
Yeah, I just tried. Looks like there are some api changes from 0.8.2.1 to 0.9.0.0 and not easy to downgrade. Are you able to upgrade your brokers?

**Comment by yyb345** [comment]
OK... Thanks for your suggestion.

**Comment by xhl1988** [comment]
@yyb345 I pushed a workaround to branch kafka-0.8.2.1. Please try it out and lemme know if there is any issue.

**Comment by yyb345** [comment]
**It works !!!** While I want to know whether this 0.8.2.1 uReplicator version has the same features as the latest master version.  In the future, you release XXX.version, if I want to use the latest features, I have to replace the corresponding consumer's interfaces, just like you modified today ?

**Comment by xhl1988** [comment]
For current 0.8.2.1 branch, it hasn't applied the fix after 1f4781dd47076ff458892c0eceb5d7eb16b09ded, but you can apply those fix yourselves.
Yes, if you want to use new released versions, you can replace the corresponding consumer's interfaces.
