### ISSUE TITLE
Kafka 0.10.X ?

### ISSUE THREAD

**Issue by yyb345** [uber/uReplicator#49]
**My source Kafka and destination Kafa version are both 0.10.2,  I use uReplicator-master version, however it comes following exceptions and only some of partitions are copied from source to destination cluster**

[2017-10-09 15:09:14,205] INFO Reconnect due to error: (kafka.consumer.SimpleConsumer)
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:83)
	at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129)
	at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:86)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
	at kafka.mirrormaker.CompactConsumerFetcherThread.processFetchRequest(CompactConsumerFetcherThread.scala:209)
	at kafka.mirrormaker.CompactConsumerFetcherThread.doWork(CompactConsumerFetcherThread.scala:192)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)

**Comment by xhl1988** [comment]
This looks like a version mismatch or config issue. Could you please post your broker and consumer configs?

**Comment by yyb345** [comment]
**source Kafka broker config**
auto.create.topics.enable=true
auto.leader.rebalance.enable=true
broker.id=863
controlled.shutdown.enable=true
controlled.shutdown.max.retries=3
default.replication.factor=2
delete.topic.enable=true
jmx_port=9393
kafka.http.metrics.host=0.0.0.0
kafka.http.metrics.port=24042
kafka.log4j.dir=/var/log/kafka
leader.imbalance.check.interval.seconds=300
leader.imbalance.per.broker.percentage=10
log.dirs=/data1/kafka/data,/data2/kafka/data,/data3/kafka/data,/data4/kafka/data,/data5/kafka/data,/data6/kafka/data,/data7/kafka/data,/data8/kafka/data,/data9/kafka/data,/data10/kafka/data,/data11/kafka/data,/data12/kafka/data
log.retention.bytes=-1
log.retention.check.interval.ms=300000
log.retention.hours=120
log.retention.ms=432000000
log.roll.hours=120
log.segment.bytes=1073741824
message.max.bytes=20485760
min.insync.replicas=1
num.io.threads=8
num.partitions=1
num.replica.fetchers=4
offsets.topic.num.partitions=50
offsets.topic.replication.factor=3
port=9092
replica.fetch.max.bytes=1048576
replica.lag.max.messages=4000
replica.lag.time.max.ms=10000
unclean.leader.election.enable=false
zookeeper.session.timeout.ms=6000
zookeeper.connect=xxx:2181,xxx:2181,xxx:2181/violet
kafka.metrics.reporters=nl.techop.kafka.KafkaHttpMetricsReporter

**uReplicator consumer config:** 

zookeeper.connect=xxx:2181/violet
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000

group.id=kloak-mirrormaker-test
consumer.id=kloakmms01-sjc1
partition.assignment.strategy=roundrobin
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=83886080
queued.max.message.chunks=5

**Comment by xhl1988** [comment]
Configs looks good to me. It is weird that some partitions works while some not. Are the working partitions always the same even partition assignment changes? Or only some workers are able to copy (not related to partitions)?

**Comment by yeziblo** [comment]
Hello yyb345! 
I have the same problem, How do you solve this problem?
Regards
