### ISSUE TITLE
SSL Consumer and Producer

### ISSUE THREAD

**Issue by llitz** [uber/uReplicator#89]
I am trying to get uReplicator working with SSL with no such luck. I can get the producer to connect to my kafka on port 9093 SSL but the consumer only connects on 9092 (automatically select when talking to zookeeper).

Is it because uReplicator uses SimpleConsumer?

**Comment by xhl1988** [comment]
Hi, @llitz , current uReplicator-Worker is using old scala-based simple consumer, which doesn't support SSL. (https://kafka.apache.org/documentation/#consumerconfigs)

**Comment by llitz** [comment]
That is what I thought (I don't know enough about the libraries being used, so I was only guessing). Do you have any plans to update the consumer side?

**Comment by xhl1988** [comment]
Yes, we plan to support the security feature by Mid 2018

**Comment by bencoughlan** [comment]
:+1:  be good to have this work with SSL/TLS security.

**Comment by josdotso** [comment]
Any updates on this? Thanks!

**Comment by xhl1988** [comment]
Our plan is delayed, so no implementation is done yet. However, we have investigated the change needed to support SSL. SimpleConsumer doesn't support SSL natively, but you can write your own SimpleConsumer and replace its BlockingChannel with this [NetworkClient](https://github.com/apache/kafka/blob/0.10.2.1/core/src/main/scala/kafka/server/ReplicaFetcherThread.scala#L78)

**Comment by FinnNk** [comment]
Any news? It would be great to have SSL support available. Cheers!

**Comment by harshach** [comment]
@FinnNk we are looking into replacing SimpleConsumer that's used in uReplicator with NetworkClient that can have SSL configs passed to connect to Secure brokers. We will keep you posted as we make progress.

**Comment by lcuquejo** [comment]
Any news?

**Comment by xhl1988** [comment]
> Any news?

We are testing security feature in staging. Will update soon.

**Comment by saisandeep** [comment]
Hi folks, raised a PR for secure consumption, this coupled with security in kafka producer provides ureplicator the ability to work with secure clusters - https://github.com/uber/uReplicator/pull/213/files

**Comment by gussell** [comment]
Tracked this for a long time is there any movement on this?

**Comment by Technoboy-** [comment]
using worker-3.0, it's already release and support

**Comment by dungnt081191** [comment]
I though by default, uReplicator using Worker3.0 when run Worker @Technoboy-

**Comment by dungnt081191** [comment]
Hi @Technoboy-  , @yangy0000  , @xhl1988 

When i use uReplicator with Kafka destination have config : ( PLAINTEXT and SSL , enable both 9092 9093 port  ) : I use 9092 in this cae.


listeners=PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093

But I have the WARN log and no message replicated .
[2019-12-06 06:34:41,986] WARN [group-uReplicator-kafka-test-topicmapping_consume-uReplicator-kafka-topicmapping-leader-finder-thread]: Failed to find leader for Set(c1.dungnt-reply-0) (kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread:72)
kafka.common.BrokerEndPointNotAvailableException: End point with security protocol PLAINTEXT not found for broker 1
	at kafka.client.ClientUtils$$anonfun$getPlaintextBrokerEndPoints$1$$anonfun$apply$5.apply(ClientUtils.scala:149)
	at kafka.client.ClientUtils$$anonfun$getPlaintextBrokerEndPoints$1$$anonfun$apply$5.apply(ClientUtils.scala:149)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.client.ClientUtils$$anonfun$getPlaintextBrokerEndPoints$1.apply(ClientUtils.scala:149)
	at kafka.client.ClientUtils$$anonfun$getPlaintextBrokerEndPoints$1.apply(ClientUtils.scala:145)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.client.ClientUtils$.getPlaintextBrokerEndPoints(ClientUtils.scala:145)
	at kafka.mirrormaker.CompactConsumerFetcherManager$LeaderFinderThread.doWork(CompactConsumerFetcherManager.scala:345)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-12-06 06:34:41,986] INFO [CompactConsumerFetcherManager-1575611930483] Added fetcher for partitions ArrayBuffer() (kafka.mirrormaker.CompactConsumerFetcherManager:66)

How can i  replicate message from SSL server ( kafka source ) to PLAINTEXT server ( kafkaf destination ) ?

**Comment by prat0318** [comment]
Some more security enhancements are now added under #334
